const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIMES = "Check Movie\nShowtimes";
const MAIN_SCREEN_SEE_MORE = "SEE MORE";
const MOVIE_LISTS_TITLE = "BEST POPULAR MOVIES AND SERIALS";
const SHOWCASE_TITLE = "SHOWCASES";
const SHOWCASE_SEE_MORE = "MORE SHOWCASES";
const ACTORS_TITLE = "BEST ACTORS";
const ACTORS_SEE_MORE = "MORE ACTORS";

const MOVIE_DETAILS_SCREEN_ACTORS_TITLES = "ACTORS";
const MOVIE_DETAILS_SCREEN_CREATORS_TITLES = "CREATORS";
const MOVIE_DETAILS_SCREEN_CREATORS_SEE_MORE = "MORE CREATORS";
const MOVIE_DETAILS_STORYlINE_TITLE = "STORYLINE";
